obj/MvrASyncTask.o: src/MvrASyncTask.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrASyncTask.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrThread.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrLog.h \
 include/MvrLog.h
obj/MvrAction.o: src/MvrAction.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrResolver.h include/mvriaTypedefs.h include/MvrActionDesired.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrAction.h include/MvrArg.h include/MvrLog.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h
obj/MvrActionAvoidFront.o: src/MvrActionAvoidFront.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrActionAvoidFront.h \
 include/mvriaTypedefs.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrAction.h include/MvrArg.h \
 include/MvrActionDesired.h include/MvrResolver.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h include/MvrLog.h
obj/MvrArg.o: src/MvrArg.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrArg.h include/mvriaTypedefs.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrLog.h \
 include/MvrArgumentBuilder.h
obj/MvrArgumentBuilder.o: src/MvrArgumentBuilder.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrArgumentBuilder.h \
 include/mvriaTypedefs.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h
obj/MvrArgumentParser.o: src/MvrArgumentParser.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrArgumentBuilder.h \
 include/mvriaTypedefs.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrArgumentParser.h
obj/MvrBasePacket.o: src/MvrBasePacket.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrBasePacket.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h
obj/MvrCondition.o: src/MvrCondition.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrLog.h include/mvriaTypedefs.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrCondition.h
obj/MvrConfig.o: src/MvrConfig.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrConfig.h include/MvrConfigArg.h include/mvriaTypedefs.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrFileParser.h include/MvrHasFileName.h \
 include/MvrArgumentBuilder.h include/MvrLog.h
obj/MvrConfigArg.o: src/MvrConfigArg.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrLog.h include/mvriaTypedefs.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrConfigArg.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrArgumentBuilder.h \
 include/MvrFileParser.h include/MvrSocket.h
obj/MvrConfigGroup.o: src/MvrConfigGroup.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrArgumentBuilder.h \
 include/mvriaTypedefs.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrConfigGroup.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h
obj/MvrDataLogger.o: src/MvrDataLogger.cpp include/mvriaOSDef.h \
 include/MvrExport.h include/MvrRobot.h include/mvriaTypedefs.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrConfig.h include/MvrDataLogger.h \
 include/MvrRobotBatteryPacketReader.h
obj/MvrDeviceConnection.o: src/MvrDeviceConnection.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrDeviceConnection.h \
 include/mvriaTypedefs.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrBasePacket.h
obj/MvrFileDeviceConnection.o: src/MvrFileDeviceConnection.cpp \
 include/MvrExport.h include/mvriaOSDef.h include/mvriaTypedefs.h \
 include/mvriaUtil.h include/mvriaTypedefs.h include/MvrLog.h \
 include/MvrMutex.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrLog.h include/MvrFileDeviceConnection.h \
 include/MvrDeviceConnection.h include/mvriaUtil.h \
 include/MvrBasePacket.h include/MvrSocket.h
obj/MvrFileParser.o: src/MvrFileParser.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrLog.h include/mvriaTypedefs.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrFileParser.h include/mvriaUtil.h
obj/MvrFunctorASyncTask.o: src/MvrFunctorASyncTask.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrFunctorASyncTask.h \
 include/mvriaTypedefs.h include/MvrASyncTask.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrThread.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrLog.h
obj/MvrInterpolation.o: src/MvrInterpolation.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrInterpolation.h include/mvriaTypedefs.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h
obj/MvrKeyHandler.o: src/MvrKeyHandler.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaInternal.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaTypedefs.h \
 include/mvriaOSDef.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrDeviceConnection.h \
 include/MvrBasePacket.h include/MvrStringInfoGroup.h include/MvrLog.h \
 include/MvrKeyHandler.h
obj/MvrLog.o: src/MvrLog.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrLog.h include/mvriaTypedefs.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrConfig.h include/MvrConfigArg.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/mvriaInternal.h include/MvrConfig.h \
 include/MvrDeviceConnection.h include/MvrBasePacket.h \
 include/MvrStringInfoGroup.h
obj/MvrLogFileConnection.o: src/MvrLogFileConnection.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrLogFileConnection.h \
 include/MvrDeviceConnection.h include/mvriaTypedefs.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrBasePacket.h include/MvrLog.h include/mvriaUtil.h
obj/MvrMode.o: src/MvrMode.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrRobot.h include/mvriaTypedefs.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/mvriaInternal.h include/MvrDeviceConnection.h \
 include/MvrStringInfoGroup.h include/MvrMode.h
obj/MvrModes.o: src/MvrModes.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrMode.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrModes.h include/MvrMode.h \
 include/MvrActionGroups.h include/MvrActionGroup.h \
 include/MvrActionColorFollow.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrAction.h include/MvrArg.h \
 include/MvrActionDesired.h include/MvrACTS.h include/MvrTcpConnection.h \
 include/MvrDeviceConnection.h include/MvrBasePacket.h \
 include/MvrSocket.h include/MvrRobot.h include/MvrRobotPacketSender.h \
 include/MvrRobotPacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h include/MvrPTZ.h \
 include/MvrCommands.h include/MvrPTZConnector.h include/mvriaInternal.h \
 include/MvrStringInfoGroup.h include/MvrGripper.h \
 include/MvrSerialConnection.h include/MvrTCMCompassRobot.h \
 include/MvrTCM2.h include/MvrRobotConfigPacketReader.h \
 include/MvrKeyHandler.h include/MvrSonyPTZ.h include/MvrAMPTU.h \
 include/MvrVCC4.h include/MvrDPPTU.h include/MvrRVisionPTZ.h \
 include/MvrSick.h include/MvrLaser.h include/MvrRangeDeviceThreaded.h \
 include/MvrRangeDevice.h include/MvrRangeBuffer.h \
 include/MvrDrawingData.h include/MvrFunctorASyncTask.h \
 include/MvrLMS2xx.h include/MvrLMS2xxPacket.h \
 include/MvrLMS2xxPacketReceiver.h include/MvrAnalogGyro.h \
 include/MvrRobotConfigPacketReader.h include/mvriaInternal.h
obj/MvrModule.o: src/MvrModule.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrModule.h include/mvriaTypedefs.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h
obj/MvrModuleLoader.o: src/MvrModuleLoader.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrModule.h include/mvriaTypedefs.h \
 include/MvrRobot.h include/MvrRobotPacketSender.h \
 include/MvrRobotPacket.h include/MvrBasePacket.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrLog.h include/MvrModuleLoader.h
obj/MvrMutex.o: src/MvrMutex.cpp include/MvrExport.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/mvriaOSDef.h include/mvriaUtil.h \
 include/mvriaTypedefs.h include/MvrLog.h include/MvrMutex.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrThread.h include/MvrLog.h \
 include/mvriaInternal.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaUtil.h include/MvrFileParser.h include/MvrHasFileName.h \
 include/MvrDeviceConnection.h include/MvrBasePacket.h \
 include/MvrStringInfoGroup.h include/MvrFunctor.h
obj/MvrPriorityResolver.o: src/MvrPriorityResolver.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrAction.h include/mvriaTypedefs.h \
 include/MvrArg.h include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrActionDesired.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrPriorityResolver.h
obj/MvrRecurrentTask.o: src/MvrRecurrentTask.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrLog.h include/mvriaTypedefs.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrASyncTask.h include/MvrThread.h \
 include/MvrLog.h include/MvrRecurrentTask.h include/MvrASyncTask.h
obj/MvrRobot.o: src/MvrRobot.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrRobot.h include/mvriaTypedefs.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrLog.h include/MvrDeviceConnection.h \
 include/MvrTcpConnection.h include/MvrDeviceConnection.h \
 include/MvrSocket.h include/MvrSerialConnection.h \
 include/MvrLogFileConnection.h include/mvriaUtil.h include/MvrSocket.h \
 include/MvrCommands.h include/MvrRobotTypes.h include/MvrSignalHandler.h \
 include/MvrPriorityResolver.h include/MvrAction.h include/MvrArg.h \
 include/MvrRangeDevice.h include/MvrRangeBuffer.h \
 include/MvrDrawingData.h include/MvrRobotConfigPacketReader.h \
 include/MvrRobotBatteryPacketReader.h include/mvriaInternal.h \
 include/MvrStringInfoGroup.h include/MvrLaser.h \
 include/MvrRangeDeviceThreaded.h include/MvrRangeDevice.h \
 include/MvrFunctorASyncTask.h include/MvrBatteryMTX.h include/MvrRobot.h \
 include/MvrRobotConnector.h include/MvrSerialConnection.h \
 include/MvrTcpConnection.h include/MvrSonarMTX.h include/MvrLCDMTX.h
obj/MvrRobotBatteryPacketReader.o: src/MvrRobotBatteryPacketReader.cpp \
 include/mvriaOSDef.h include/MvrExport.h include/MvrRobot.h \
 include/mvriaTypedefs.h include/MvrRobotPacketSender.h \
 include/MvrRobotPacket.h include/MvrBasePacket.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrRobotPacket.h include/MvrCommands.h \
 include/MvrRobotBatteryPacketReader.h
obj/MvrRobotConfig.o: src/MvrRobotConfig.cpp include/mvriaOSDef.h \
 include/MvrExport.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaTypedefs.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrActionDesired.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/mvriaInternal.h include/MvrDeviceConnection.h \
 include/MvrStringInfoGroup.h include/MvrAnalogGyro.h \
 include/MvrRobotConfig.h
obj/MvrRobotConnector.o: src/MvrRobotConnector.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrRobot.h include/mvriaTypedefs.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrSick.h include/MvrLaser.h include/MvrRangeDeviceThreaded.h \
 include/MvrRangeDevice.h include/MvrRangeBuffer.h \
 include/MvrDrawingData.h include/MvrFunctorASyncTask.h \
 include/MvrLMS2xx.h include/MvrLMS2xxPacket.h \
 include/MvrLMS2xxPacketReceiver.h include/MvrDeviceConnection.h \
 include/mvriaInternal.h include/MvrStringInfoGroup.h \
 include/MvrCommands.h include/MvrSonarConnector.h \
 include/MvrSerialConnection.h include/MvrTcpConnection.h \
 include/MvrSocket.h include/MvrRobotConnector.h \
 include/MvrBatteryConnector.h include/MvrRobotConnector.h
obj/MvrRobotJoyHandler.o: src/MvrRobotJoyHandler.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrRobotJoyHandler.h \
 include/mvriaTypedefs.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrCommands.h include/mvriaInternal.h \
 include/MvrDeviceConnection.h include/MvrStringInfoGroup.h
obj/MvrRobotPacket.o: src/MvrRobotPacket.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrRobotPacket.h include/mvriaTypedefs.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h
obj/MvrRobotPacketReaderThread.o: src/MvrRobotPacketReaderThread.cpp \
 include/MvrExport.h include/mvriaOSDef.h include/MvrLog.h \
 include/mvriaTypedefs.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h \
 include/MvrRobotPacketReceiver.h include/MvrSyncTask.h \
 include/MvrTaskState.h include/MvrSensorReading.h include/MvrTransform.h \
 include/MvrCondition.h include/MvrSyncLoop.h include/MvrASyncTask.h \
 include/MvrThread.h include/MvrRobotPacketReaderThread.h \
 include/MvrRobotParams.h include/MvrConfig.h include/MvrConfigArg.h \
 include/MvrFileParser.h include/MvrHasFileName.h \
 include/MvrActionDesired.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrRobotPacketReaderThread.h
obj/MvrRobotPacketReceiver.o: src/MvrRobotPacketReceiver.cpp \
 include/MvrExport.h include/mvriaOSDef.h include/MvrLog.h \
 include/mvriaTypedefs.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrLogFileConnection.h \
 include/MvrDeviceConnection.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrBasePacket.h include/MvrDeviceConnection.h \
 include/mvriaUtil.h include/MvrRobotPacketReceiver.h \
 include/MvrRobotPacket.h
obj/MvrRobotPacketSender.o: src/MvrRobotPacketSender.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrDeviceConnection.h \
 include/mvriaTypedefs.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrBasePacket.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h
obj/MvrRobotParams.o: src/MvrRobotParams.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaInternal.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaTypedefs.h \
 include/mvriaOSDef.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrDeviceConnection.h \
 include/MvrBasePacket.h include/MvrStringInfoGroup.h \
 include/MvrRobotParams.h
obj/MvrRobotTypes.o: src/MvrRobotTypes.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrRobotTypes.h include/mvriaUtil.h \
 include/mvriaTypedefs.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h \
 include/MvrRobotParams.h include/MvrConfig.h include/MvrConfigArg.h \
 include/MvrFileParser.h include/MvrHasFileName.h include/MvrLog.h
obj/MvrSensorReading.o: src/MvrSensorReading.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrSensorReading.h \
 include/mvriaUtil.h include/MvrTransform.h
obj/MvrSerialConnection.o: src/MvrSerialConnection.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrLog.h \
 include/MvrSerialConnection.h include/MvrDeviceConnection.h \
 include/mvriaUtil.h include/MvrBasePacket.h
obj/MvrSignalHandler.o: src/MvrSignalHandler.cpp include/MvrExport.h \
 include/MvrLog.h include/mvriaTypedefs.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/mvriaInternal.h include/MvrConfig.h include/MvrConfigArg.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrDeviceConnection.h \
 include/MvrBasePacket.h include/MvrStringInfoGroup.h \
 include/MvrSignalHandler.h include/MvrASyncTask.h include/MvrThread.h
obj/MvrSimpleConnection.o: src/MvrSimpleConnection.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrRobot.h include/mvriaTypedefs.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h include/MvrLog.h \
 include/MvrMutex.h include/mvriaTypedefs.h include/MvrFunctor.h \
 include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrRobotPacketReceiver.h \
 include/MvrSyncTask.h include/MvrTaskState.h include/MvrSensorReading.h \
 include/MvrTransform.h include/MvrCondition.h include/MvrSyncLoop.h \
 include/MvrASyncTask.h include/MvrThread.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrConfig.h include/MvrConfigArg.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrActionDesired.h \
 include/MvrResolver.h include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrLaser.h include/MvrRangeDeviceThreaded.h \
 include/MvrRangeDevice.h include/MvrRangeBuffer.h \
 include/MvrDrawingData.h include/MvrFunctorASyncTask.h \
 include/mvriaInternal.h include/MvrDeviceConnection.h \
 include/MvrStringInfoGroup.h include/MvrSimpleConnector.h \
 include/MvrSerialConnection.h include/MvrTcpConnection.h \
 include/MvrSocket.h include/MvrRobotConnector.h \
 include/MvrLaserConnector.h
obj/MvrSocket.o: src/MvrSocket.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrLog.h include/mvriaTypedefs.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrFunctor.h include/MvrSocket.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h
obj/MvrStringInfoGroup.o: src/MvrStringInfoGroup.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrStringInfoGroup.h include/mvriaUtil.h \
 include/mvriaTypedefs.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h
obj/MvrSyncLoop.o: src/MvrSyncLoop.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrLog.h include/MvrRobot.h \
 include/MvrRobotPacketSender.h include/MvrRobotPacket.h \
 include/MvrBasePacket.h include/mvriaUtil.h \
 include/MvrRobotPacketReceiver.h include/MvrSyncTask.h \
 include/MvrTaskState.h include/MvrSensorReading.h include/MvrTransform.h \
 include/MvrCondition.h include/MvrSyncLoop.h include/MvrASyncTask.h \
 include/MvrThread.h include/MvrRobotPacketReaderThread.h \
 include/MvrRobotParams.h include/MvrConfig.h include/MvrConfigArg.h \
 include/MvrFileParser.h include/MvrHasFileName.h \
 include/MvrActionDesired.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h include/MvrSyncLoop.h
obj/MvrSyncTask.o: src/MvrSyncTask.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrLog.h include/MvrSyncTask.h \
 include/MvrTaskState.h
obj/MvrSystemStatus.o: src/MvrSystemStatus.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/mvriaUtil.h include/mvriaTypedefs.h \
 include/MvrLog.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaOSDef.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/mvriaInternal.h include/MvrConfig.h \
 include/MvrConfigArg.h include/mvriaUtil.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrDeviceConnection.h \
 include/MvrBasePacket.h include/MvrStringInfoGroup.h \
 include/MvrASyncTask.h include/MvrThread.h include/MvrSystemStatus.h
obj/MvrThread.o: src/MvrThread.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/MvrLog.h include/mvriaTypedefs.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrThread.h include/MvrLog.h include/MvrSignalHandler.h \
 include/MvrASyncTask.h include/MvrThread.h
obj/MvrTransform.o: src/MvrTransform.cpp include/MvrExport.h \
 include/mvriaOSDef.h include/MvrTransform.h include/mvriaTypedefs.h \
 include/mvriaUtil.h include/MvrLog.h include/MvrMutex.h \
 include/mvriaTypedefs.h include/MvrFunctor.h include/mvriaOSDef.h \
 include/MvrArgumentParser.h include/MvrArgumentBuilder.h
obj/md5.o: src/md5.cpp include/md5.h
obj/mvriaUtil.o: src/mvriaUtil.cpp include/MvrExport.h include/mvriaOSDef.h \
 include/mvriaInternal.h include/MvrMutex.h include/mvriaTypedefs.h \
 include/MvrFunctor.h include/mvriaTypedefs.h include/mvriaOSDef.h \
 include/MvrConfig.h include/MvrConfigArg.h include/mvriaUtil.h \
 include/MvrLog.h include/MvrArgumentParser.h \
 include/MvrArgumentBuilder.h include/MvrFileParser.h \
 include/MvrHasFileName.h include/MvrDeviceConnection.h \
 include/MvrBasePacket.h include/MvrStringInfoGroup.h include/mvriaUtil.h \
 include/MvrSick.h include/MvrRobotPacket.h include/MvrLaser.h \
 include/MvrRangeDeviceThreaded.h include/MvrRangeDevice.h \
 include/MvrRangeBuffer.h include/MvrTransform.h \
 include/MvrSensorReading.h include/MvrDrawingData.h \
 include/MvrFunctorASyncTask.h include/MvrASyncTask.h include/MvrThread.h \
 include/MvrCondition.h include/MvrLMS2xx.h include/MvrLMS2xxPacket.h \
 include/MvrLMS2xxPacketReceiver.h include/MvrUrg.h include/MvrLMS1XX.h \
 include/MvrS3Series.h include/MvrUrg_2_0.h include/MvrSZSeries.h \
 include/MvrSonarMTX.h include/MvrRobot.h include/MvrRobotPacketSender.h \
 include/MvrRobotPacketReceiver.h include/MvrSyncTask.h \
 include/MvrTaskState.h include/MvrSyncLoop.h \
 include/MvrRobotPacketReaderThread.h include/MvrRobotParams.h \
 include/MvrActionDesired.h include/MvrResolver.h \
 include/MvrInterpolation.h include/MvrKeyHandler.h \
 include/MvrBatteryMTX.h include/MvrRobotConnector.h \
 include/MvrSerialConnection.h include/MvrTcpConnection.h \
 include/MvrSocket.h include/MvrLCDMTX.h include/MvrSerialConnection.h \
 include/MvrTcpConnection.h
